import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:run_recorder/run_recorder.dart';

// Golden vectors generated by scripts/gps_distance/reference.py (spec v1.2).
// `flutter test` runs with the package root as cwd, so the repo-root fixture
// is two levels up.
Map<String, dynamic> _loadVectors() {
  final file = File('../../fixtures/gps_distance_vectors.json');
  return jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
}

double? _num(Map<String, dynamic> m, String key) =>
    (m[key] as num?)?.toDouble();

GpsEvent _event(Map<String, dynamic> ev) => switch (ev['type']) {
      'fix' => GpsFixEvent(
          t: _num(ev, 't')!,
          lat: _num(ev, 'lat')!,
          lng: _num(ev, 'lng')!,
          accuracyM: _num(ev, 'acc'),
          speedMps: _num(ev, 'speed'),
          speedAccuracyMps: _num(ev, 'speedAcc'),
          bearingDeg: _num(ev, 'bearing'),
        ),
      'steps' =>
        GpsStepsEvent(t: _num(ev, 't')!, count: (ev['count'] as num).toInt()),
      'finish' => GpsFinishEvent(t: _num(ev, 't')!),
      _ => throw StateError('unknown event type ${ev['type']}'),
    };

void _apply(GpsDistanceEstimator e, GpsEvent ev) {
  switch (ev) {
    case GpsFixEvent():
      e.addFix(
        t: ev.t,
        lat: ev.lat,
        lng: ev.lng,
        accuracyM: ev.accuracyM,
        speedMps: ev.speedMps,
        speedAccuracyMps: ev.speedAccuracyMps,
        bearingDeg: ev.bearingDeg,
      );
    case GpsStepsEvent():
      e.addSteps(ev.t, ev.count);
    case GpsFinishEvent():
      e.finish(ev.t);
  }
}

void main() {
  final vectors = _loadVectors();
  final tolerance = (vectors['tolerance_m'] as num).toDouble();
  final posTolerance = (vectors['position_tolerance_deg'] as num).toDouble();
  final scenarios =
      (vectors['scenarios'] as List).cast<Map<String, dynamic>>();

  test('fixture is spec v1.3 and carries every scenario', () {
    expect(vectors['spec'], 'gps-distance-estimator v1.3');
    expect(GpsDistanceEstimator.specVersion, '1.3');
    expect(scenarios.length, greaterThanOrEqualTo(29));
  });

  test('constants match the fixture', () {
    final c = (vectors['constants'] as Map).cast<String, num>();
    expect(c['EARTH_RADIUS_M'], GpsDistanceEstimator.earthRadiusM);
    expect(c['Q_ACCEL'], GpsDistanceEstimator.qAccel);
    expect(c['MIN_POS_SIGMA_M'], GpsDistanceEstimator.minPosSigmaM);
    expect(c['INIT_VEL_VAR'], GpsDistanceEstimator.initVelVar);
    expect(c['MIN_SPEED_SIGMA_MPS'], GpsDistanceEstimator.minSpeedSigmaMps);
    expect(
        c['DEFAULT_SPEED_SIGMA_MPS'], GpsDistanceEstimator.defaultSpeedSigmaMps);
    expect(c['MAX_SPEED_SIGMA_MPS'], GpsDistanceEstimator.maxSpeedSigmaMps);
    expect(c['STATIONARY_SPEED_MPS'], GpsDistanceEstimator.stationarySpeedMps);
    expect(c['POS_ONLY_STATIONARY_SPEED_MPS'],
        GpsDistanceEstimator.posOnlyStationarySpeedMps);
    expect(c['GAP_S'], GpsDistanceEstimator.gapS);
    expect(c['FRESH_FIX_S'], GpsDistanceEstimator.freshFixS);
    expect(c['STRIDE_WINDOW_STEPS'], GpsDistanceEstimator.strideWindowSteps);
    expect(c['MIN_STRIDE_M'], GpsDistanceEstimator.minStrideM);
    expect(c['MAX_STRIDE_M'], GpsDistanceEstimator.maxStrideM);
    expect(c['STRIDE_EMA_ALPHA'], GpsDistanceEstimator.strideEmaAlpha);
    expect(c['GATE_CHI2'], GpsDistanceEstimator.gateChi2);
    expect(c['GATE_MAX_REJECTS'], GpsDistanceEstimator.gateMaxRejects);
    expect(c['R_SCALE_ALPHA'], GpsDistanceEstimator.rScaleAlpha);
    expect(c['R_SCALE_MIN'], GpsDistanceEstimator.rScaleMin);
    expect(c['R_SCALE_MAX'], GpsDistanceEstimator.rScaleMax);
    expect(c['XCHECK_TAU_S'], GpsDistanceEstimator.xcheckTauS);
    expect(c['XCHECK_MIN_S'], GpsDistanceEstimator.xcheckMinS);
    expect(c['XCHECK_ENTER_ABS_MPS'], GpsDistanceEstimator.xcheckEnterAbsMps);
    expect(c['XCHECK_ENTER_REL'], GpsDistanceEstimator.xcheckEnterRel);
    expect(c['XCHECK_EXIT_ABS_MPS'], GpsDistanceEstimator.xcheckExitAbsMps);
    expect(c['XCHECK_EXIT_REL'], GpsDistanceEstimator.xcheckExitRel);
    expect(c['XCHECK_PERSIST_S'], GpsDistanceEstimator.xcheckPersistS);
    expect(c['XCHECK_MAX_SPAN_S'], GpsDistanceEstimator.xcheckMaxSpanS);
    expect(c['DEBIAS_FULL_MPS'], GpsDistanceEstimator.debiasFullMps);
    expect(c['DEBIAS_ZERO_MPS'], GpsDistanceEstimator.debiasZeroMps);
    expect(c['DSCALE_TAU_S'], GpsDistanceEstimator.dscaleTauS);
    expect(c['DSCALE_MIN_S'], GpsDistanceEstimator.dscaleMinS);
    expect(c['DSCALE_MIN'], GpsDistanceEstimator.dscaleMin);
    expect(c['DSCALE_MAX'], GpsDistanceEstimator.dscaleMax);
    expect(c['DSCALE_MIN_SPEED_MPS'], GpsDistanceEstimator.dscaleMinSpeedMps);
    expect(c['DSCALE_MAX_TURN_DEG'], GpsDistanceEstimator.dscaleMaxTurnDeg);
    expect(c['ZUPT_NO_STEP_S'], GpsDistanceEstimator.zuptNoStepS);
    expect(c['ZUPT_VEL_SIGMA_MPS'], GpsDistanceEstimator.zuptVelSigmaMps);
    expect(c['ZUPT_DOPPLER_OVERRIDE_MPS'],
        GpsDistanceEstimator.zuptDopplerOverrideMps);
    expect(c['ZUPT_RELEASE_M'], GpsDistanceEstimator.zuptReleaseM);
    expect(c['STOP_HALF_WINDOW_S'], GpsDistanceEstimator.stopHalfWindowS);
    expect(c['STOP_MIN_HALF_FIXES'], GpsDistanceEstimator.stopMinHalfFixes);
    expect(c['STOP_SPEED_MPS'], GpsDistanceEstimator.stopSpeedMps);
    expect(c['STOP_RADIUS_M'], GpsDistanceEstimator.stopRadiusM);
    // Every fixture constant is pinned above; a new one fails here until it is.
    expect(c.length, 44);
  });

  group('golden vectors', () {
    for (final s in scenarios) {
      test(s['name'] as String, () {
        final e = GpsDistanceEstimator(
          maxSpeedMps: _num(s, 'maxSpeedMps')!,
          expectedIntervalS: _num(s, 'expectedIntervalS')!,
          initialStrideM: _num(s, 'initialStrideM'),
        );
        final events = (s['events'] as List)
            .cast<Map<String, dynamic>>()
            .map(_event)
            .toList();
        final expected = s['expected'] as Map<String, dynamic>;
        final after = (expected['distanceAfterEachEventM'] as List)
            .map((v) => (v as num).toDouble())
            .toList();
        expect(after, hasLength(events.length));
        for (var i = 0; i < events.length; i++) {
          _apply(e, events[i]);
          expect(e.distanceM, closeTo(after[i], tolerance),
              reason: 'distance after event $i (${events[i].runtimeType})');
        }
        expect(e.gpsDistanceM,
            closeTo(_num(expected, 'gpsDistanceM')!, tolerance));
        expect(e.stepDistanceM,
            closeTo(_num(expected, 'stepDistanceM')!, tolerance));
        final stride = _num(expected, 'strideM');
        if (stride == null) {
          expect(e.strideM, isNull);
        } else {
          expect(e.strideM, isNotNull);
          expect(e.strideM!, closeTo(stride, tolerance));
        }
        expect(e.rejectedFixes, expected['rejectedFixes']);
        expect(e.zuptFixes, expected['zuptFixes']);
        expect(e.dopplerTrusted, expected['dopplerTrusted']);
        expect(e.rScale, closeTo(_num(expected, 'rScale')!, 1e-6));
        expect(
            e.dopplerScale, closeTo(_num(expected, 'dopplerScale')!, 1e-6));
      });
    }
  });

  group('smoothed golden vectors', () {
    for (final s in scenarios) {
      test(s['name'] as String, () {
        final events = (s['events'] as List)
            .cast<Map<String, dynamic>>()
            .map(_event)
            .toList();
        final want = s['smoothed'] as Map<String, dynamic>;
        final got = smoothDistance(
          events,
          maxSpeedMps: _num(s, 'maxSpeedMps')!,
          expectedIntervalS: _num(s, 'expectedIntervalS')!,
          initialStrideM: _num(s, 'initialStrideM'),
        );
        final after = (want['distanceAfterEachEventM'] as List)
            .map((v) => (v as num).toDouble())
            .toList();
        expect(got.cumulativeM, hasLength(events.length));
        for (var i = 0; i < events.length; i++) {
          expect(got.cumulativeM[i], closeTo(after[i], tolerance),
              reason: 'smoothed distance after event $i');
        }
        expect(got.distanceM, closeTo(_num(want, 'distanceM')!, tolerance));
        expect(got.gpsDistanceM,
            closeTo(_num(want, 'gpsDistanceM')!, tolerance));
        expect(got.stepDistanceM,
            closeTo(_num(want, 'stepDistanceM')!, tolerance));
        expect(got.stoppedFixes, want['stoppedFixes']);
        final positions = want['positions'] as List;
        expect(got.positions, hasLength(positions.length));
        for (var i = 0; i < positions.length; i++) {
          final w = positions[i] as List?;
          final p = got.positions[i];
          if (w == null) {
            expect(p, isNull, reason: 'position $i');
            continue;
          }
          expect(p, isNotNull, reason: 'position $i');
          expect(p!.lat, closeTo((w[0] as num).toDouble(), posTolerance),
              reason: 'lat $i');
          expect(p.lng, closeTo((w[1] as num).toDouble(), posTolerance),
              reason: 'lng $i');
        }
      });
    }
  });

  group('non-finite input', () {
    GpsDistanceEstimator running() {
      final e = GpsDistanceEstimator();
      for (var i = 0; i < 5; i++) {
        e.addFix(
          t: i.toDouble(),
          lat: 40 + i * 0.000025,
          lng: -75,
          accuracyM: 4,
          speedMps: 2.7,
          speedAccuracyMps: 0.4,
          bearingDeg: 0,
        );
      }
      return e;
    }

    test('a NaN or infinite time, latitude or longitude credits nothing', () {
      final e = running();
      final before = e.distanceM;
      expect(e.addFix(t: double.nan, lat: 40.0002, lng: -75), 0);
      expect(e.addFix(t: double.infinity, lat: 40.0002, lng: -75), 0);
      expect(e.addFix(t: 5, lat: double.nan, lng: -75), 0);
      expect(e.addFix(t: 5, lat: 40.0002, lng: double.negativeInfinity), 0);
      expect(e.distanceM, before);
      expect(e.distanceM.isFinite, isTrue);
    });

    test('a NaN accuracy, speed or bearing falls back instead of poisoning', () {
      final e = running();
      e.addFix(
        t: 5,
        lat: 40.000125,
        lng: -75,
        accuracyM: double.nan,
        speedMps: double.nan,
        speedAccuracyMps: double.nan,
        bearingDeg: double.nan,
      );
      e.addFix(
        t: 6,
        lat: 40.00015,
        lng: -75,
        accuracyM: double.infinity,
        speedMps: 2.7,
        speedAccuracyMps: double.infinity,
        bearingDeg: double.infinity,
      );
      expect(e.distanceM.isFinite, isTrue);
      expect(e.gpsDistanceM, greaterThan(0));
    });

    test('a NaN step time is ignored and finish(NaN) commits nothing', () {
      final e = running();
      e.addSteps(double.nan, 100);
      e.finish(double.nan);
      expect(e.stepDistanceM, 0);
      expect(e.distanceM.isFinite, isTrue);
    });
  });

  group('constructor', () {
    test('a non-finite or sub-second interval hint behaves as 1 s', () {
      for (final it in [double.nan, double.infinity, 0.5, -3.0]) {
        final e = GpsDistanceEstimator(expectedIntervalS: it);
        e.addFix(t: 0, lat: 40, lng: -75);
        e.addFix(t: 11, lat: 40.0003, lng: -75);
        expect(e.gpsDistanceM, 0, reason: 'interval $it');
      }
    });

    test('initial stride is kept only when finite and in range', () {
      expect(GpsDistanceEstimator(initialStrideM: 1.1).strideM, 1.1);
      expect(GpsDistanceEstimator(initialStrideM: 0.3).strideM, isNull);
      expect(GpsDistanceEstimator(initialStrideM: 2.6).strideM, isNull);
      expect(GpsDistanceEstimator(initialStrideM: double.nan).strideM, isNull);
    });
  });
}
