import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:run_recorder/run_recorder.dart';

// Golden vectors generated by scripts/gps_distance/reference.py (spec v1.1).
// `flutter test` runs with the package root as cwd, so the repo-root fixture
// is two levels up.
Map<String, dynamic> _loadVectors() {
  final file = File('../../fixtures/gps_distance_vectors.json');
  return jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
}

double? _num(Map<String, dynamic> m, String key) =>
    (m[key] as num?)?.toDouble();

void _apply(GpsDistanceEstimator e, Map<String, dynamic> ev) {
  switch (ev['type']) {
    case 'fix':
      e.addFix(
        t: _num(ev, 't')!,
        lat: _num(ev, 'lat')!,
        lng: _num(ev, 'lng')!,
        accuracyM: _num(ev, 'acc'),
        speedMps: _num(ev, 'speed'),
        speedAccuracyMps: _num(ev, 'speedAcc'),
        bearingDeg: _num(ev, 'bearing'),
      );
    case 'steps':
      e.addSteps(_num(ev, 't')!, (ev['count'] as num).toInt());
    case 'finish':
      e.finish(_num(ev, 't')!);
    default:
      fail('unknown event type ${ev['type']}');
  }
}

void main() {
  final vectors = _loadVectors();
  final tolerance = (vectors['tolerance_m'] as num).toDouble();
  final scenarios =
      (vectors['scenarios'] as List).cast<Map<String, dynamic>>();

  test('fixture is spec v1.1 and carries every scenario', () {
    expect(vectors['spec'], 'gps-distance-estimator v1.1');
    expect(scenarios, isNotEmpty);
  });

  test('constants match the fixture', () {
    final c = (vectors['constants'] as Map).cast<String, num>();
    expect(c['EARTH_RADIUS_M'], GpsDistanceEstimator.earthRadiusM);
    expect(c['Q_ACCEL'], GpsDistanceEstimator.qAccel);
    expect(c['MIN_POS_SIGMA_M'], GpsDistanceEstimator.minPosSigmaM);
    expect(c['INIT_VEL_VAR'], GpsDistanceEstimator.initVelVar);
    expect(c['MIN_SPEED_SIGMA_MPS'], GpsDistanceEstimator.minSpeedSigmaMps);
    expect(
        c['DEFAULT_SPEED_SIGMA_MPS'], GpsDistanceEstimator.defaultSpeedSigmaMps);
    expect(c['MAX_SPEED_SIGMA_MPS'], GpsDistanceEstimator.maxSpeedSigmaMps);
    expect(c['STATIONARY_SPEED_MPS'], GpsDistanceEstimator.stationarySpeedMps);
    expect(c['POS_ONLY_STATIONARY_SPEED_MPS'],
        GpsDistanceEstimator.posOnlyStationarySpeedMps);
    expect(c['GAP_S'], GpsDistanceEstimator.gapS);
    expect(c['FRESH_FIX_S'], GpsDistanceEstimator.freshFixS);
    expect(c['STRIDE_WINDOW_STEPS'], GpsDistanceEstimator.strideWindowSteps);
    expect(c['MIN_STRIDE_M'], GpsDistanceEstimator.minStrideM);
    expect(c['MAX_STRIDE_M'], GpsDistanceEstimator.maxStrideM);
    expect(c['STRIDE_EMA_ALPHA'], GpsDistanceEstimator.strideEmaAlpha);
  });

  group('golden vectors', () {
    for (final s in scenarios) {
      test(s['name'] as String, () {
        final e = GpsDistanceEstimator(
          maxSpeedMps: _num(s, 'maxSpeedMps')!,
          expectedIntervalS: _num(s, 'expectedIntervalS')!,
          initialStrideM: _num(s, 'initialStrideM'),
        );
        final events = (s['events'] as List).cast<Map<String, dynamic>>();
        final expected = s['expected'] as Map<String, dynamic>;
        final after = (expected['distanceAfterEachEventM'] as List)
            .map((v) => (v as num).toDouble())
            .toList();
        expect(after, hasLength(events.length));
        for (var i = 0; i < events.length; i++) {
          _apply(e, events[i]);
          expect(e.distanceM, closeTo(after[i], tolerance),
              reason: 'distance after event $i (${events[i]['type']})');
        }
        expect(e.gpsDistanceM,
            closeTo(_num(expected, 'gpsDistanceM')!, tolerance));
        expect(e.stepDistanceM,
            closeTo(_num(expected, 'stepDistanceM')!, tolerance));
        final stride = _num(expected, 'strideM');
        if (stride == null) {
          expect(e.strideM, isNull);
        } else {
          expect(e.strideM, isNotNull);
          expect(e.strideM!, closeTo(stride, tolerance));
        }
      });
    }
  });

  group('non-finite input', () {
    GpsDistanceEstimator running() {
      final e = GpsDistanceEstimator();
      for (var i = 0; i < 5; i++) {
        e.addFix(
          t: i.toDouble(),
          lat: 40 + i * 0.000025,
          lng: -75,
          accuracyM: 4,
          speedMps: 2.7,
          speedAccuracyMps: 0.4,
          bearingDeg: 0,
        );
      }
      return e;
    }

    test('a NaN or infinite time, latitude or longitude credits nothing', () {
      final e = running();
      final before = e.distanceM;
      expect(e.addFix(t: double.nan, lat: 40.0002, lng: -75), 0);
      expect(e.addFix(t: double.infinity, lat: 40.0002, lng: -75), 0);
      expect(e.addFix(t: 5, lat: double.nan, lng: -75), 0);
      expect(e.addFix(t: 5, lat: 40.0002, lng: double.negativeInfinity), 0);
      expect(e.distanceM, before);
      expect(e.distanceM.isFinite, isTrue);
    });

    test('a NaN accuracy, speed or bearing falls back instead of poisoning', () {
      final e = running();
      e.addFix(
        t: 5,
        lat: 40.000125,
        lng: -75,
        accuracyM: double.nan,
        speedMps: double.nan,
        speedAccuracyMps: double.nan,
        bearingDeg: double.nan,
      );
      e.addFix(
        t: 6,
        lat: 40.00015,
        lng: -75,
        accuracyM: double.infinity,
        speedMps: 2.7,
        speedAccuracyMps: double.infinity,
        bearingDeg: double.infinity,
      );
      expect(e.distanceM.isFinite, isTrue);
      expect(e.gpsDistanceM, greaterThan(0));
    });

    test('a NaN step time is ignored and finish(NaN) commits nothing', () {
      final e = running();
      e.addSteps(double.nan, 100);
      e.finish(double.nan);
      expect(e.stepDistanceM, 0);
      expect(e.distanceM.isFinite, isTrue);
    });
  });

  group('constructor', () {
    test('a non-finite or sub-second interval hint behaves as 1 s', () {
      for (final it in [double.nan, double.infinity, 0.5, -3.0]) {
        final e = GpsDistanceEstimator(expectedIntervalS: it);
        e.addFix(t: 0, lat: 40, lng: -75);
        e.addFix(t: 11, lat: 40.0003, lng: -75);
        expect(e.gpsDistanceM, 0, reason: 'interval $it');
      }
    });

    test('initial stride is kept only when finite and in range', () {
      expect(GpsDistanceEstimator(initialStrideM: 1.1).strideM, 1.1);
      expect(GpsDistanceEstimator(initialStrideM: 0.3).strideM, isNull);
      expect(GpsDistanceEstimator(initialStrideM: 2.6).strideM, isNull);
      expect(GpsDistanceEstimator(initialStrideM: double.nan).strideM, isNull);
    });
  });
}
