import 'package:flutter/material.dart';

/// App-wide theme and design tokens: "Dusk, refined" (decisions § 1768).
///
/// One coral accent in both brightnesses — bright [coral] on dark, [coralDeep]
/// on light — with lilac / [violet] as the secondary, over near-neutral greys
/// that carry only a trace of violet. Web's `app.css` holds the same values;
/// `apps/web/src/lib/contrast_guard.test.ts` asserts the lockstep.
class AppTheme {
  /// The brand hue. No longer painted anywhere: it seeds the Material
  /// tonal palettes that the roles below do not override (surface
  /// containers, outline, onSurfaceVariant), which is where the trace of
  /// violet in the neutrals comes from.
  static const Color dusk = Color(0xFF3A2E5C);

  /// Dark scaffold, raised surface (cards, sheets) and the scrolled-under
  /// app bar, in that order of height.
  static const Color night = Color(0xFF121117);
  static const Color nightRaised = Color(0xFF1C1A24);
  static const Color nightHigh = Color(0xFF24212E);

  /// Light scaffold and the scrolled-under app bar. Light cards and sheets
  /// are white.
  static const Color snow = Color(0xFFFAF9FB);
  static const Color snowDim = Color(0xFFECE9F1);

  /// Text on dark, and its muted variant.
  static const Color mist = Color(0xFFF3F1F7);
  static const Color mistMuted = Color(0xFFA9A4B6);

  /// Text on light, and its muted variant.
  static const Color ink = Color(0xFF1A1722);
  static const Color inkMuted = Color(0xFF5F5A6B);

  /// The accent on dark: a fill (buttons, FAB, selected chip) under [onCoral],
  /// and a mark (the selected nav icon) on every dark surface.
  static const Color coral = Color(0xFFF08A5D);
  static const Color onCoral = Color(0xFF1A0E08);

  /// The accent on light, deep enough to be both the fill under white type
  /// (4.77:1) and a mark on the light surfaces (4.54:1 on [snow]).
  static const Color coralDeep = Color(0xFFC24E24);

  /// The secondary accent: [lilac] on dark, [violet] on light.
  static const Color lilac = Color(0xFFB9A7E8);
  static const Color violet = Color(0xFF5B4B8A);

  static const Color error = Color(0xFFD8594C);

  /// The one line token per brightness: every divider, hairline outline and
  /// hand-drawn border resolves to this, and each clears WCAG 1.4.11's 3:1
  /// non-text minimum against the surfaces it is drawn on (light 3.45:1 on
  /// [snow], 3.6:1 on white; dark 3.47:1 on [nightRaised], 3.18:1 on
  /// [nightHigh]).
  static const Color snowLine = Color(0xFF8A8496);
  static const Color nightLine = Color(0xFF736D85);

  /// The product typeface, bundled by this package (SIL OFL 1.1, see
  /// `fonts/OFL.txt`; generated by `assets/fonts/gen-manrope.py`).
  static const String fontFamily = 'Manrope';

  /// How far a subtree may be dimmed to read as out-of-scope — an adjacent
  /// month's calendar cell, a retired piece of gear.
  ///
  /// `Opacity` composites the whole subtree, so when that subtree contains text
  /// this is a contrast multiplier on every glyph in it, bounded above by WCAG
  /// 1.4.3 rather than by taste. Both surfaces it dims wrap an `InkWell`, so
  /// 1.4.3's incidental-text exemption does not apply to either. The previous
  /// per-site values (0.55 and 0.65) put muted type at 2.511:1 and 3.427:1;
  /// this is the one value both clear, derived in
  /// `apps/mobile_android/test/dimmed_subtree_opacity_test.dart`.
  static const double dimmedSubtreeOpacity = 0.85;

  static ThemeData get light {
    final scheme = ColorScheme.fromSeed(
      seedColor: dusk,
      brightness: Brightness.light,
    ).copyWith(
      primary: coralDeep,
      onPrimary: Colors.white,
      secondary: violet,
      onSecondary: Colors.white,
      surface: Colors.white,
      onSurface: ink,
      onSurfaceVariant: inkMuted,
      error: error,
      outlineVariant: snowLine,
    );
    return ThemeData(
      colorScheme: scheme,
      fontFamily: fontFamily,
      package: 'ui_kit',
      scaffoldBackgroundColor: snow,
      useMaterial3: true,
      splashFactory: InkRipple.splashFactory,
      // The seeded surface tint is a cool lavender (#64558F) that, laid over
      // the scaffold at the elevation-3 opacity, is barely a step. Light
      // therefore separates the scrolled-under bar with its own fill
      // (1.15:1 off snow) plus a real shadow.
      appBarTheme: AppBarThemeData(
        backgroundColor: WidgetStateColor.resolveWith(
          (states) => states.contains(WidgetState.scrolledUnder)
              ? snowDim
              : snow,
        ),
        foregroundColor: ink,
        elevation: 0,
        scrolledUnderElevation: 3,
        surfaceTintColor: Colors.transparent,
        shadowColor: ink,
      ),
      filledButtonTheme: FilledButtonThemeData(
        style: FilledButton.styleFrom(
          backgroundColor: coralDeep,
          foregroundColor: Colors.white,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
          ),
          padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
          textStyle: const TextStyle(
            fontWeight: FontWeight.w600,
            letterSpacing: 0.2,
          ),
        ),
      ),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
          ),
          padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
          ),
          padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
        ),
      ),
      textButtonTheme: TextButtonThemeData(
        style: TextButton.styleFrom(
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
          ),
          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 14),
        ),
      ),
      // A white card on the snow scaffold is only a 1.05:1 step, so card
      // separation comes from the hairline outline, not the fill. The margin
      // is vertical-only so a card's left edge is always its parent's padding
      // edge; the 4 stays because 49 stacked-card sites carry no gap of their
      // own and Material's default margin was supplying it.
      cardTheme: const CardThemeData(
        color: Colors.white,
        elevation: 0,
        margin: EdgeInsets.symmetric(vertical: 4),
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.all(Radius.circular(12)),
          side: BorderSide(color: snowLine),
        ),
      ),
      inputDecorationTheme: InputDecorationThemeData(
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
      ),
      bottomSheetTheme: const BottomSheetThemeData(
        backgroundColor: Colors.white,
        modalBackgroundColor: Colors.white,
        surfaceTintColor: Colors.transparent,
        elevation: 0,
        modalElevation: 0,
        showDragHandle: true,
        dragHandleColor: snowLine,
        clipBehavior: Clip.antiAlias,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
        ),
      ),
      textTheme: const TextTheme(
        labelSmall: TextStyle(
          fontSize: 11,
          fontWeight: FontWeight.w500,
          letterSpacing: 0.5,
        ),
      ),
      // The glyph, not the fill, is what owes 1.4.11's 3:1 here — the FAB
      // carries its own elevation and shadow. White on coralDeep is 4.77:1.
      floatingActionButtonTheme: const FloatingActionButtonThemeData(
        backgroundColor: coralDeep,
        foregroundColor: Colors.white,
      ),
      chipTheme: ChipThemeData(
        backgroundColor: Colors.transparent,
        selectedColor: coralDeep,
        side: const BorderSide(color: inkMuted),
        // RawChip resolves only labelStyle.color as a WidgetStateProperty
        // (never the whole TextStyle, never secondaryLabelStyle), so the
        // selected/unselected fork must live on the color itself. It also
        // takes `chipTheme.labelStyle ?? chipDefaults.labelStyle` — an OR, not
        // a merge — so overriding this DISPLACES M3's labelLarge outright, and
        // the size has to be restated here or the label falls through to
        // whatever the ambient style happens to be. These four values ARE
        // labelLarge, identical across all three of Material's locale
        // geometries, and `inherit` stays true so the locale's own family and
        // baseline still arrive by merge.
        labelStyle: TextStyle(
          fontSize: 14,
          fontWeight: FontWeight.w500,
          letterSpacing: 0.1,
          height: 1.43,
          color: WidgetStateColor.resolveWith(
            (states) =>
                states.contains(WidgetState.selected) ? scheme.onPrimary : ink,
          ),
        ),
        checkmarkColor: scheme.onPrimary,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(20),
        ),
      ),
      navigationBarTheme: NavigationBarThemeData(
        backgroundColor: snow,
        indicatorColor: coralDeep.withOpacity(0.18),
        surfaceTintColor: Colors.transparent,
        // The selected icon sits INSIDE the indicator, so the tint is the
        // background it owes 3:1 against, not the bar: coralDeep on the pill
        // is 3.56:1.
        iconTheme: WidgetStateProperty.resolveWith(
          (states) => IconThemeData(
            color: states.contains(WidgetState.selected) ? coralDeep : inkMuted,
            size: 24,
          ),
        ),
        labelTextStyle: WidgetStateProperty.resolveWith(
          (states) => TextStyle(
            fontSize: 12,
            fontWeight: states.contains(WidgetState.selected)
                ? FontWeight.w600
                : FontWeight.w500,
            color: states.contains(WidgetState.selected) ? ink : inkMuted,
          ),
        ),
      ),
      dividerColor: snowLine,
      // Divider ignores `dividerColor` under Material 3 and falls back to
      // colorScheme.outlineVariant, so the token has to be pinned in all
      // three places or a drawn hairline and a Divider beside it land on
      // different greys.
      dividerTheme: const DividerThemeData(color: snowLine),
      extensions: const [AppSemanticColors.light],
    );
  }

  static ThemeData get dark {
    final scheme = ColorScheme.fromSeed(
      seedColor: dusk,
      brightness: Brightness.dark,
    ).copyWith(
      primary: coral,
      onPrimary: onCoral,
      secondary: lilac,
      onSecondary: night,
      surface: nightRaised,
      onSurface: mist,
      onSurfaceVariant: mistMuted,
      error: error,
      outlineVariant: nightLine,
    );
    return ThemeData(
      colorScheme: scheme,
      fontFamily: fontFamily,
      package: 'ui_kit',
      scaffoldBackgroundColor: night,
      useMaterial3: true,
      splashFactory: InkRipple.splashFactory,
      // A shadow is not available against night, so dark carries the whole
      // separation in the fill: rising to nightHigh is a 1.19:1 step.
      appBarTheme: AppBarThemeData(
        backgroundColor: WidgetStateColor.resolveWith(
          (states) =>
              states.contains(WidgetState.scrolledUnder) ? nightHigh : night,
        ),
        foregroundColor: mist,
        elevation: 0,
        scrolledUnderElevation: 3,
        surfaceTintColor: Colors.transparent,
        shadowColor: night,
      ),
      filledButtonTheme: FilledButtonThemeData(
        style: FilledButton.styleFrom(
          backgroundColor: coral,
          foregroundColor: onCoral,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
          ),
          padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
          textStyle: const TextStyle(
            fontWeight: FontWeight.w600,
            letterSpacing: 0.2,
          ),
        ),
      ),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
          ),
          padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
          ),
          padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
        ),
      ),
      textButtonTheme: TextButtonThemeData(
        style: TextButton.styleFrom(
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
          ),
          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 14),
        ),
      ),
      cardTheme: const CardThemeData(
        color: nightRaised,
        elevation: 0,
        margin: EdgeInsets.symmetric(vertical: 4),
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.all(Radius.circular(12)),
          side: BorderSide(color: nightLine),
        ),
      ),
      inputDecorationTheme: InputDecorationThemeData(
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
      ),
      bottomSheetTheme: const BottomSheetThemeData(
        backgroundColor: nightRaised,
        modalBackgroundColor: nightRaised,
        surfaceTintColor: Colors.transparent,
        elevation: 0,
        modalElevation: 0,
        showDragHandle: true,
        dragHandleColor: nightLine,
        clipBehavior: Clip.antiAlias,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
        ),
      ),
      textTheme: const TextTheme(
        labelSmall: TextStyle(
          fontSize: 11,
          fontWeight: FontWeight.w500,
          letterSpacing: 0.5,
        ),
      ),
      floatingActionButtonTheme: const FloatingActionButtonThemeData(
        backgroundColor: coral,
        foregroundColor: onCoral,
      ),
      chipTheme: ChipThemeData(
        backgroundColor: Colors.transparent,
        selectedColor: coral,
        side: const BorderSide(color: mistMuted),
        labelStyle: TextStyle(
          fontSize: 14,
          fontWeight: FontWeight.w500,
          letterSpacing: 0.1,
          height: 1.43,
          color: WidgetStateColor.resolveWith(
            (states) => states.contains(WidgetState.selected)
                ? scheme.onPrimary
                : mist,
          ),
        ),
        checkmarkColor: scheme.onPrimary,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(20),
        ),
      ),
      navigationBarTheme: NavigationBarThemeData(
        backgroundColor: night,
        indicatorColor: coral.withOpacity(0.22),
        surfaceTintColor: Colors.transparent,
        iconTheme: WidgetStateProperty.resolveWith(
          (states) => IconThemeData(
            color: states.contains(WidgetState.selected)
                ? coral
                : mist.withOpacity(0.55),
            size: 24,
          ),
        ),
        labelTextStyle: WidgetStateProperty.resolveWith(
          (states) => TextStyle(
            fontSize: 12,
            fontWeight: states.contains(WidgetState.selected)
                ? FontWeight.w600
                : FontWeight.w500,
            color: states.contains(WidgetState.selected)
                ? mist
                : mist.withOpacity(0.55),
          ),
        ),
      ),
      dividerColor: nightLine,
      dividerTheme: const DividerThemeData(color: nightLine),
      extensions: const [AppSemanticColors.dark],
    );
  }
}

/// Semantic status colours outside the Material scheme: success, warning,
/// danger, and the segment-crown gold. Every on*/base pair is tuned to
/// >= 4.5:1 WCAG AA contrast and every base to >= 3:1 against its
/// brightness's scaffold background — the scheme's own error/onError pair
/// computes below AA (3.85:1 in light), which is why danger exists.
@immutable
class AppSemanticColors extends ThemeExtension<AppSemanticColors> {
  const AppSemanticColors({
    required this.success,
    required this.onSuccess,
    required this.warning,
    required this.onWarning,
    required this.danger,
    required this.onDanger,
    required this.crown,
    required this.onCrown,
  });

  final Color success;
  final Color onSuccess;
  final Color warning;
  final Color onWarning;
  final Color danger;
  final Color onDanger;
  final Color crown;
  final Color onCrown;

  static const AppSemanticColors light = AppSemanticColors(
    success: Color(0xFF2E6B3C),
    onSuccess: AppTheme.snow,
    warning: Color(0xFF8A5712),
    onWarning: AppTheme.snow,
    danger: Color(0xFFA93B2E),
    onDanger: AppTheme.snow,
    crown: Color(0xFF7A5C10),
    onCrown: AppTheme.snow,
  );

  static const AppSemanticColors dark = AppSemanticColors(
    success: Color(0xFF8CC49B),
    onSuccess: AppTheme.night,
    warning: Color(0xFFE6A23C),
    onWarning: AppTheme.night,
    danger: Color(0xFFEC8B7A),
    onDanger: AppTheme.night,
    crown: Color(0xFFE0BE4E),
    onCrown: AppTheme.night,
  );

  // Brightness-matched fallback so a harness that pumps a bare MaterialApp
  // (no AppTheme) renders sane status colours instead of throwing.
  static AppSemanticColors of(BuildContext context) =>
      ofTheme(Theme.of(context));

  static AppSemanticColors ofTheme(ThemeData theme) =>
      theme.extension<AppSemanticColors>() ??
      (theme.brightness == Brightness.dark ? dark : light);

  @override
  AppSemanticColors copyWith({
    Color? success,
    Color? onSuccess,
    Color? warning,
    Color? onWarning,
    Color? danger,
    Color? onDanger,
    Color? crown,
    Color? onCrown,
  }) {
    return AppSemanticColors(
      success: success ?? this.success,
      onSuccess: onSuccess ?? this.onSuccess,
      warning: warning ?? this.warning,
      onWarning: onWarning ?? this.onWarning,
      danger: danger ?? this.danger,
      onDanger: onDanger ?? this.onDanger,
      crown: crown ?? this.crown,
      onCrown: onCrown ?? this.onCrown,
    );
  }

  @override
  AppSemanticColors lerp(ThemeExtension<AppSemanticColors>? other, double t) {
    if (other is! AppSemanticColors) return this;
    return AppSemanticColors(
      success: Color.lerp(success, other.success, t)!,
      onSuccess: Color.lerp(onSuccess, other.onSuccess, t)!,
      warning: Color.lerp(warning, other.warning, t)!,
      onWarning: Color.lerp(onWarning, other.onWarning, t)!,
      danger: Color.lerp(danger, other.danger, t)!,
      onDanger: Color.lerp(onDanger, other.onDanger, t)!,
      crown: Color.lerp(crown, other.crown, t)!,
      onCrown: Color.lerp(onCrown, other.onCrown, t)!,
    );
  }
}
