#!/usr/bin/env node
// Gives the Apple Watch app its Supabase project in a release, and proves the
// shipped bundle has it.
//
// The watch reads `SupabaseURL` / `SupabaseAnonKey` from its Info.plist, which
// expands them from the build settings `SUPABASE_URL` / `SUPABASE_ANON_KEY`
// (WatchAuth.swift's `SupabaseEnvironment`). `flutter build ipa` defines
// neither: `--dart-define-from-file` reaches Xcode only as Flutter's
// `DART_DEFINES`, one base64 list in Generated.xcconfig that the Dart build
// decodes and nothing on watchOS reads. So every release built before this
// script shipped a watch whose sign-in was fail-closed (decisions § 1810).
//
// `write` turns the two values in the environment into the untracked
// `Flutter/WatchRuntime.xcconfig` that the committed `Flutter/WatchApp.xcconfig`
// `#include?`s. `verify` reads the shipped `WatchApp.app/Info.plist` (as JSON,
// from `plutil -convert json`) and fails unless both keys came through equal
// to what was written. Neither prints a value — only its shape.
//
// Usage:
//   SUPABASE_URL=… SUPABASE_ANON_KEY=… node scripts/ios_watch_runtime_config.mjs write <out.xcconfig>
//   plutil -convert json -o - <Info.plist> | SUPABASE_URL=… SUPABASE_ANON_KEY=… node scripts/ios_watch_runtime_config.mjs verify -
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

export const URL_SETTING = 'SUPABASE_URL';
export const KEY_SETTING = 'SUPABASE_ANON_KEY';
export const URL_INFO_KEY = 'SupabaseURL';
export const KEY_INFO_KEY = 'SupabaseAnonKey';

/**
 * An origin and nothing else: the watch appends `/auth/v1/…` and `/rest/v1/…`
 * itself, so a path or a trailing slash is a malformed request later.
 */
const URL_SHAPE = /^https:\/\/[A-Za-z0-9.-]+(:[0-9]{1,5})?$/;

/**
 * A legacy anon JWT (three base64url segments) or an `sb_publishable_` key.
 * The character set is also what makes the value safe to write into an
 * xcconfig unescaped: no `$` to expand, no `/` to start a comment, no quote,
 * no whitespace.
 */
const KEY_SHAPE = /^[A-Za-z0-9._-]+$/;

/**
 * The URL with the trailing slash an operator may have pasted removed, after
 * checking it is an https origin. Throws naming the setting, never the value.
 * @param {string | undefined} raw
 */
export function normalizeUrl(raw) {
	const value = (raw ?? '').trim().replace(/\/$/, '');
	if (value === '') throw new Error(`${URL_SETTING} is empty.`);
	if (!URL_SHAPE.test(value)) {
		throw new Error(
			`${URL_SETTING} is not an https origin (https://host[:port], no path). The watch builds its ` +
				'GoTrue and PostgREST URLs by appending to it, so anything else is a request that fails on the wrist.',
		);
	}
	return value;
}

/**
 * The anon key, after refusing anything that is not a client key. A
 * `service_role` JWT or an `sb_secret_` key in this secret would ship a key
 * that bypasses RLS inside a binary anyone can unzip.
 * @param {string | undefined} raw
 */
export function normalizeKey(raw) {
	const value = (raw ?? '').trim();
	if (value === '') throw new Error(`${KEY_SETTING} is empty.`);
	if (!KEY_SHAPE.test(value)) {
		throw new Error(`${KEY_SETTING} holds characters no Supabase client key has (allowed: A-Z a-z 0-9 . _ -).`);
	}
	if (value.startsWith('sb_secret_')) {
		throw new Error(`${KEY_SETTING} is an sb_secret_ key. A client binary carries the publishable key only.`);
	}
	const parts = value.split('.');
	if (parts.length === 3) {
		let role;
		try {
			role = JSON.parse(Buffer.from(parts[1], 'base64url').toString('utf8')).role;
		} catch {
			throw new Error(`${KEY_SETTING} has the shape of a JWT and its payload does not decode.`);
		}
		if (role !== 'anon') {
			throw new Error(`${KEY_SETTING} is a JWT whose role is not anon. A client binary carries the anon key only.`);
		}
	} else if (!value.startsWith('sb_publishable_')) {
		throw new Error(`${KEY_SETTING} is neither an anon JWT nor an sb_publishable_ key.`);
	}
	return value;
}

/**
 * An xcconfig line runs to its end except that `//` starts a comment, so
 * `https://host` would be read as `https:`. `$()` expands to nothing, and
 * putting one after every slash leaves no two slashes adjacent.
 * @param {string} value
 */
export function xcconfigEscape(value) {
	return value.replaceAll('/', '/$()');
}

/** @param {{ url: string, key: string }} values */
export function renderXcconfig({ url, key }) {
	return (
		'// Generated by scripts/ios_watch_runtime_config.mjs in release-ios.yml. Untracked;\n' +
		'// never commit it. Flutter/WatchApp.xcconfig includes it when present.\n' +
		`${URL_SETTING} = ${xcconfigEscape(url)}\n` +
		`${KEY_SETTING} = ${key}\n`
	);
}

/**
 * Reverses what Xcode does to a setting before it lands in the plist, so a
 * test can assert the round trip without Xcode.
 * @param {string} line
 */
export function expandEscapes(line) {
	return line.replaceAll('$()', '');
}

/** @param {string} value */
function shapeOf(value) {
	return `length ${value.length}`;
}

/**
 * Checks the shipped Info.plist against the values the release was given.
 * Returns the summary lines to print; throws naming the key that is wrong.
 * @param {Record<string, unknown>} info
 * @param {{ url: string, key: string }} expected
 */
export function verifyInfo(info, expected) {
	/** @type {string[]} */ const problems = [];
	/** @param {string} infoKey @param {string} want @param {string} setting */
	const check = (infoKey, want, setting) => {
		const got = info[infoKey];
		if (typeof got !== 'string' || got.trim() === '') {
			problems.push(`${infoKey} is empty — ${setting} was undefined for the WatchApp target, so sign-in on the wrist is fail-closed.`);
		} else if (got.includes('$(')) {
			problems.push(`${infoKey} still holds an unexpanded build-setting reference, so sign-in on the wrist is fail-closed.`);
		} else if (got !== want) {
			problems.push(
				`${infoKey} is set but differs from the release secret (built ${shapeOf(got)}, secret ${shapeOf(want)}). ` +
					'An xcconfig comment or escape has eaten part of it.',
			);
		}
	};
	check(URL_INFO_KEY, expected.url, URL_SETTING);
	check(KEY_INFO_KEY, expected.key, KEY_SETTING);
	if (problems.length > 0) throw new Error(problems.join(' '));
	return [
		`${URL_INFO_KEY}: https origin present, ${shapeOf(expected.url)}, equal to the release secret`,
		`${KEY_INFO_KEY}: present, ${shapeOf(expected.key)}, equal to the release secret`,
	];
}

/** @param {string[]} argv @param {NodeJS.ProcessEnv} env */
export function main(argv, env) {
	const [command, path] = argv;
	try {
		const expected = { url: normalizeUrl(env[URL_SETTING]), key: normalizeKey(env[KEY_SETTING]) };
		if (command === 'write' && path) {
			writeFileSync(path, renderXcconfig(expected));
			console.log(`Wrote ${URL_SETTING} (${shapeOf(expected.url)}) and ${KEY_SETTING} (${shapeOf(expected.key)}) to ${path}`);
			return 0;
		}
		if (command === 'verify' && path) {
			const info = JSON.parse(readFileSync(path === '-' ? 0 : path, 'utf8'));
			for (const line of verifyInfo(info, expected)) console.log(line);
			return 0;
		}
		console.log('::error::Usage: node scripts/ios_watch_runtime_config.mjs write <out.xcconfig> | verify <Info.json|->');
		return 1;
	} catch (e) {
		console.log(`::error::${e instanceof Error ? e.message : String(e)}`);
		return 1;
	}
}

if (process.argv[1] === fileURLToPath(import.meta.url)) process.exit(main(process.argv.slice(2), process.env));
